# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

# Trigger a workflow on any push to the main branch or pull request
# event --> push, pull, merge, delete
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      # - staging
      # - projection

jobs:
  test:

    runs-on: ubuntu-latest  # containers: windows-latest, macos-latest

    steps:

    # step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

    # step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

    # step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    # step 4: Run tests
      - name: Run tests
        run: pytest
