# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI


#triger a work flow on nay push to the main branch or pull request
#event -->push,pull,merge,delete


   #____>trigger an event
on:
  push:
    branches:
    - main
  pull_request:
    branches:
     - main
     # - staging
     # - projection


jobs:
  test:

    runs-on: ubuntu-latest  # containers  windows-lates,mac-os

    steps:

    #step-1 check out the code from the repository
    - name: check out code
    - uses: actions/checkout@v2

    #step-2 setup python environmet
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
      
    #step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #step4: run test
    - name: Run tests
      run: pytest
